<?php

namespace AppBundle\Repository;

/**
 * TexmexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TexmexRepository extends \Doctrine\ORM\EntityRepository
{
    public function getResults()
    {

        $results = $this->createQueryBuilder('texmex')
            ->getQuery()
            ->getResult();

        return $results;
    }
    
}
