<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Token;
/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends \Doctrine\ORM\EntityRepository
{

        public function getResults(string $email, string $token)
        {

            $results = $this->createQueryBuilder('token')
                ->where('token.email = :email')
                ->andWhere('token.token = :token')
                ->setParameters([
                    'email' => $email,
                    'token' => $token
                ])
                ->getQuery()
                ->getResult();


            return $results;
        }

    public function deleteToken(string $email, string $token)
    {

        $results = $this->getEntityManager()->createQueryBuilder()
            ->delete(Token::class, 'token')
            ->where('token.email = :email')
            ->andWhere('token.token = :token')
            ->setParameters([
                'email' => $email,
                'token' => $token
            ])
            ->getQuery()
            ->getResult();

    }


}
