<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function getResults(string $firstname)
    {

        $results = $this->createQueryBuilder('user')
            ->where('user.firstName = :firstName')
            ->setParameters([
                'firstName' => $firstname,
            ])
            ->getQuery()
            ->getOneOrNullResult();


        return $results;
    }


}
