# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin@admin.fr:
                        password: $2y$12$RGMYCGhvPGmd02xxYLAyXOVItw1T/ESRj2lBVp9fc.rCLNXrqFnWS
                        roles: 'ROLE_ADMIN'

        our_db_provider:
            entity:
                class: AppBundle:User
                #propriete utilisée comme identifiant
                property: username
        #creation d'un provider qui regroupe les autres providers
        all_providers:
            chain:
                providers: [ in_memory, our_db_provider ]

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
            ROLE_ADMIN: ROLE_USER

    access_control:
                    # require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_ADMIN }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            provider: our_db_provider

        main:
            anonymous: ~
            # activate different ways to authenticate
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: app.user.login
                check_path: app.user.login
                #path de redirection après login
                default_target_path: app.user.redirect

            logout:
                path: app.user.logout
                target: app.default.index

            provider: all_providers